<?xml version="1.0"?>
<!DOCTYPE stock[
<!ELEMENT stock (new-car | used-car)*>
<!ELEMENT new-car (model, price)>
<!ELEMENT used-car (model, price, mileage, condition?)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT mileage (#PCDATA)>
<!ELEMENT condition (#PCDATA)> 
]>

    <stock>
        <new-car>
            <model> Reneault </model>
            <price> 20 000</price>
            <mileage> blanc </mileage>
            <condition> 1 </condition>
        </new-car>
        <used-car>
            <model> Fiat </model>
            <price> 14 000</price>
            <mileage> rouge </mileage>
            <condition> 0 </condition>
        </used-car>
    </stock>


    
